version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: ~/circleci-android-with-font
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: ./create_dockerfiles.rb