version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: ~/circleci-android-with-font
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to docker
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run: ./create_dockerfiles.rb

workflows:
  version: 2
  on_master:
    jobs:
      - build
  scheduled_update:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
